### ISSUE TITLE
下载的图片都是缩略图 | it downloads thumbnails

### ISSUE THREAD

**Issue by postblue** [Un-index/imgbb-bulk#4]
下载的图片都是缩略图.
这个怎么解决

**Comment by deontic** [comment]
你好，谢谢你让我知道。你可以先试试这个网站：https://deontic.github.io/imgBB-web-bulk-downloader/
据我所知，这个网站并不下载缩略图。如果你真的希望我修复这个软件包，你可以让我知道，但这将花费你一颗星 🙂



> Thanks for letting me know. You can try the site for now. 
>As far as I am aware the site does not download thumbnails.

**Comment by shinji257** [comment]
Just tested and it does grab the incorrect and smaller image in many cases.  I don't know if it does it all the time but it was easy enough to find examples.  I had to go through the gallery I was on and find a SFW example for you.  Filenames are also currently adding "hosted at ImgBB" to them due to using the title of the page to set the filename.

https://ibb.co/BwdcYmD

Script retrieved version: 640x907
Actual size: 1280x1814

It seems that the method to grab the url is flawed as it grabs the last one in the HTML.  
The CHV.obj.image_viewer.image variable in the very last script has an escaped version of the correct url along with size information for validation.  Other areas to get the correct url is as follows:

In head block:
og:image metadata info
link rel entry

In body block:
The download link which also has an isolated variable in the link for the original filename

EDIT: Interestingly the generic version @ https://github.com/deontic/chevereto-bulk-downloader works fine.  It grabs the correct image but it still uses the title of the page to set the filename.  I wish I could see that code to know what you did on that version differently than this one.

**Comment by deontic** [comment]
you can see it here: https://github.com/deontic/chevereto-bulk-downloader/blob/main/docs/index.html

i think i wrote that part from scratch again, honestly dont remember though

**Comment by postblue** [comment]
时间过久，关闭。
